// These SVGs are explanatory sketches, not licensed reproductions of a standards database.
const item=(id,name,kind,contexts,aliases,visual,does,distinction,notation='')=>({id,name,kind,contexts,aliases,visual,does,distinction,notation});

export const catalog=[
  item('no-contact','Normally open contact','Wired control',['control'],['normally open contact','no contact','open contact','two parallel lines','two vertical bars','relay contact open','contactor auxiliary no','13 14'], 'Two separated parallel bars on a control rung.','Closes when its associated device actuates, completing this control path.','A physical contact; a PLC XIC looks similar but examines a bit.','—| |—'),
  item('nc-contact','Normally closed contact','Wired control',['control'],['normally closed contact','nc contact','closed contact','two lines with diagonal slash','two bars with slash','stop contact','push to break','21 22'], 'Two parallel bars crossed by a diagonal slash.','Opens when its associated device actuates, interrupting this control path.','The normal state is the device’s unactuated reference state; verify the drawing legend.','—|/|—'),
  item('no-pushbutton','Normally open pushbutton','Operator device',['control'],['start button','start pushbutton','momentary pushbutton no','push to make','normally open pushbutton','button open'], 'Normally open contact with a pushbutton actuator above it.','Closes only while the button is pressed, unless a separate latch circuit holds the command.','The button itself does not latch a motor starter.','START / NO'),
  item('nc-pushbutton','Normally closed pushbutton','Operator device',['control'],['stop button','stop pushbutton','push to break button','normally closed pushbutton','button with slash','momentary stop'], 'Normally closed contact with a pushbutton actuator.','Opens its control path when pressed.','A regular stop button is not automatically a safety-rated emergency stop.','STOP / NC'),
  item('estop','Emergency-stop actuator','Operator device',['control'],['emergency stop','e stop','estop','mushroom button','red mushroom','safety stop'], 'Mushroom-head actuator above a contact depiction.','Manually initiates a stop function in an appropriately engineered safety circuit.','The symbol alone does not establish safety performance or wiring architecture.','E-STOP'),
  item('relay-coil','Relay or contactor coil','Wired control',['control'],['relay coil','contactor coil','coil circle','circle labeled km','circle labeled cr','electromagnet coil','a1 a2'], 'Circle with coil tag between two control wires.','A rated control voltage magnetizes the device and moves its associated contacts.','The coil does not carry the motor’s three-phase load current.','KM1 / A1–A2'),
  item('contactor-power','Three-pole contactor','Motor power',['power'],['three pole contactor','motor starter contacts','three open switches','three phases through contacts','l1 l2 l3 t1 t2 t3','km main contacts','contactor main poles'], 'Three linked normally open contacts, one per phase.','Applies or removes three-phase power to a motor when its separate coil changes state.','An auxiliary contact gives only indirect pickup feedback.','KM1'),
  item('overload-contact','Overload trip contact (NC)','Motor protection',['control'],['overload contact','overload healthy','ol contact','95 96','thermal trip contact','motor overload normally closed','overload nc'], 'Normally closed control contact tagged OL, often identified 95–96.','Opens the starter control path when the overload relay trips in this common arrangement.','This contact is separate from the current-sensing elements in the motor power path.','OL1 / 95–96'),
  item('overload-sensing','Overload current-sensing element','Motor protection',['power'],['overload sensing','overload heater','thermal overload element','three overload blocks','motor protection current sensing','ol power circuit'], 'Current-sensing element in a motor phase path.','Monitors motor current or heating behavior for overload protection.','It does not replace required short-circuit protection.','OL1'),
  item('breaker','Circuit breaker','Power distribution',['power'],['circuit breaker','breaker','cb','qf','switch with trip','three pole breaker','feeder breaker'], 'Switching contacts in a protected branch, shown here as one-line equipment.','Opens a circuit and can interrupt specified fault current within its ratings.','Ratings, trip functions, and isolation suitability depend on the exact device.','QF1 / CB'),
  item('fuse','Fuse','Power distribution',['power'],['fuse','fusible link','fused circuit','fu symbol','small rectangle in line'], 'Small rectangular fuse element in series with a conductor.','Melts to interrupt excessive current according to its characteristics.','Replacement and coordination must follow equipment documentation.','FU1'),
  item('disconnect','Disconnect switch','Power distribution',['power'],['disconnect','isolator','knife switch','open switch on feeder','switch disconnector'], 'Open knife-switch contact in a power conductor.','Provides a means to disconnect a circuit when applied and rated correctly.','A plain disconnect is not necessarily an overcurrent protective device.','QS1'),
  item('transformer','Transformer','Power distribution',['power'],['transformer','two coils','two windings','magnetic core','step down transformer','primary secondary'], 'Two windings with a core between them.','Transfers AC energy by magnetic coupling and changes voltage according to winding ratio.','A transformer is not a generator; its secondary grounding depends on design.','T1'),
  item('motor-3ph','Three-phase motor','Load',['power'],['motor','three phase motor','circle with m','m inside circle','motor 3 tilde','fan motor','pump motor'], 'Circle marked M and 3~ with three supply leads.','Converts three-phase electrical power into shaft torque.','An auxiliary contact alone cannot prove this motor rotates.','M1 / 3~'),
  item('pe-ground','Protective earth','Grounding',['power','control'],['protective earth','earth ground','ground symbol','three horizontal lines decreasing','pe','equipment ground'], 'Three horizontal bars of decreasing width beneath a conductor.','Identifies the protective equipment grounding connection.','Not the normal motor-current return or a substitute for neutral.','PE'),
  item('pilot-lamp','Pilot light / indicator','Operator device',['control'],['lamp','pilot light','indicator lamp','circle with x','circle with cross','run light','fault light'], 'Circle containing an X.','Lights to communicate status when its circuit is energized.','A lit run lamp may report a command rather than physical motion; trace its circuit.','HL1'),
  item('plc-di','PLC digital input','PLC interface',['control','instrument'],['plc input','digital input','di channel','input module','field switch to plc','input card'], 'Field contact connected to a PLC input block.','Reads an electrical on/off field signal into the controller.','The module’s wiring and input common depend on its specification.','DI'),
  item('plc-do','PLC digital output','PLC interface',['control'],['plc output','digital output','do channel','output module','output card','plc commands coil'], 'PLC output block connected to an external load or interface.','Switches a compatible low-power load or interface under program control.','Check output type and ratings before driving a coil.','DO'),
  item('x ic','XIC - Examine If Closed','PLC ladder',['ladder'],['xic','examine if closed','plc normally open','ladder no contact','bit true contact','two vertical lines in ladder'], 'Two upright bars on a PLC ladder rung.','Makes its rung condition true when the addressed bit is 1.','It is a software instruction; it does not prove a physical contact is closed.','XIC / —| |—'),
  item('xio','XIO - Examine If Open','PLC ladder',['ladder'],['xio','examine if open','plc normally closed','ladder nc contact','bit false contact','slashed ladder contact'], 'Two bars with a diagonal slash on a PLC ladder rung.','Makes its rung condition true when the addressed bit is 0.','It tests a bit; it is not necessarily a physical normally closed field contact.','XIO / —|/|—'),
  item('ote','OTE - Output Energize','PLC ladder',['ladder'],['ote','output energize','ladder coil','plc coil','parentheses output','output instruction'], 'Parenthesized output symbol at the right of a rung.','Sets the addressed bit when preceding rung conditions are true and clears it when false.','A program bit or output command is not proof that a motor actually started.','OTE / —( )—'),
  item('vfd','Variable-frequency drive','Motor power',['power'],['vfd','variable frequency drive','inverter drive','ac drive','rectifier inverter motor','speed drive'], 'Block labeled VFD between three-phase input and motor output.','Controls motor speed by generating a controlled-frequency and voltage output.','The motor-side waveform is not ordinary fixed-frequency utility AC.','VFD1'),
  item('proximity','Proximity sensor','Field device',['instrument','control'],['proximity sensor','prox switch','inductive sensor','detect metal without contact','non contact sensor'], 'Sensor block with target-sensing arcs.','Detects a nearby target and sends a signal to controls.','Wiring and output type vary by sensor model.','B1 / PROX'),
  item('limit-switch','Limit switch','Field device',['instrument','control'],['limit switch','mechanical position switch','roller lever switch','end of travel switch','actuated by cam'], 'Switch contact with a mechanical lever actuator.','Changes contact state when a moving part reaches its position.','The contact can be NO or NC; inspect the actual contact marking.','LS1'),
  item('terminal','Terminal block','Connection',['control','power'],['terminal block','terminal strip','numbered terminal','wire landing point','screw terminal','x1 terminal'], 'Small connection circle or block in an uninterrupted conductor.','Provides a labeled point for joining and servicing conductors.','A terminal does not by itself protect or switch the circuit.','X1:1'),
  item('capacitor','Capacitor','Electronic component',['control','power'],['capacitor','two plates','two parallel lines no wire between','capacitance','c1'], 'Two parallel plates separated by a gap.','Stores energy in an electric field and opposes sudden voltage change.','Can resemble a NO contact in a rough verbal description; check circuit context and tag.','C1')
];

const common=`fill="none" stroke="#173b52" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"`;
const line=(x1,y1,x2,y2)=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/>`;
const txt=(x,y,s,size=13)=>`<text x="${x}" y="${y}" text-anchor="middle" font-family="Arial,sans-serif" font-size="${size}" font-weight="700" fill="#173b52" stroke="none">${s}</text>`;
const contact=(nc=false)=>`${line(12,60,93,60)}${line(93,38,93,82)}${line(147,38,147,82)}${line(147,60,228,60)}${nc?line(81,84,158,36):''}`;
const coil=(tag='KM1')=>`${line(12,60,91,60)}<circle cx="120" cy="60" r="29"/>${line(149,60,228,60)}${txt(120,65,tag,12)}`;
const box=(label)=>`${line(12,60,55,60)}<rect x="55" y="27" width="130" height="66" rx="4"/>${line(185,60,228,60)}${txt(120,65,label)}`;

export function symbolSvg(id){
 let inner='';
 switch(id){
  case 'no-contact':case 'x ic':inner=contact();break;
  case 'nc-contact':case 'xio':case 'overload-contact':inner=contact(true)+(id==='overload-contact'?txt(120,107,'OL1 95–96',10):'');break;
  case 'no-pushbutton':case 'nc-pushbutton':inner=contact(id==='nc-pushbutton')+line(120,16,120,40)+line(101,16,139,16);break;
  case 'estop':inner=contact(true)+line(120,18,120,39)+`<path d="M95 18 Q120 -5 145 18 Z"/>`;break;
  case 'relay-coil':inner=coil();break;
  case 'ote':inner=`${line(12,60,89,60)}<path d="M109 36 Q88 60 109 84 M131 36 Q152 60 131 84"/>${line(151,60,228,60)}`;break;
  case 'contactor-power':inner=[32,60,88].map(y=>`${line(25,y,100,y)}${line(100,y-10,100,y+10)}${line(140,y-10,140,y+10)}${line(140,y,215,y)}`).join('')+txt(120,113,'KM1',10);break;
  case 'overload-sensing':inner=[32,60,88].map(y=>`${line(20,y,90,y)}<rect x="90" y="${y-10}" width="60" height="20"/>${line(150,y,220,y)}${txt(120,y+4,'OL',9)}`).join('');break;
  case 'breaker':inner=[33,60,87].map(y=>`${line(20,y,98,y)}<circle cx="98" cy="${y}" r="2" fill="#173b52"/><circle cx="143" cy="${y}" r="2" fill="#173b52"/>${line(98,y,133,y-15)}${line(143,y,220,y)}`).join('');break;
  case 'disconnect':inner=`${line(12,60,95,60)}<circle cx="95" cy="60" r="2" fill="#173b52"/>${line(95,60,145,35)}<circle cx="151" cy="60" r="2" fill="#173b52"/>${line(151,60,228,60)}`;break;
  case 'fuse':inner=`${line(12,60,85,60)}<rect x="85" y="44" width="70" height="32"/>${line(85,60,155,60)}${line(155,60,228,60)}`;break;
  case 'transformer':inner=`${line(12,60,65,60)}<path d="M65 60 c0 -28 30 -28 30 0 c0 28 30 28 30 0 M135 60 c0 -28 30 -28 30 0 c0 28 30 28 30 0"/>${line(195,60,228,60)}${line(128,18,128,102)}${line(133,18,133,102)}`;break;
  case 'motor-3ph':inner=`${line(12,35,75,35)}${line(12,60,75,60)}${line(12,85,75,85)}<circle cx="135" cy="60" r="53"/>${txt(135,59,'M',26)}${txt(135,80,'3~',13)}`;break;
  case 'pe-ground':inner=`${line(120,10,120,55)}${line(67,55,173,55)}${line(84,68,156,68)}${line(100,81,140,81)}${line(112,94,128,94)}`;break;
  case 'pilot-lamp':inner=`${line(12,60,82,60)}<circle cx="120" cy="60" r="38"/>${line(94,34,146,86)}${line(146,34,94,86)}${line(158,60,228,60)}`;break;
  case 'plc-di':inner=`${line(12,60,66,60)}${line(66,42,66,78)}${line(91,42,91,78)}${line(91,60,107,60)}<rect x="107" y="28" width="109" height="64"/>${txt(162,65,'PLC DI',13)}`;break;
  case 'plc-do':inner=`<rect x="18" y="28" width="112" height="64"/>${txt(74,65,'PLC DO',13)}${line(130,60,185,60)}<circle cx="199" cy="60" r="14"/>`;break;
  case 'vfd':inner=`${line(12,60,50,60)}<rect x="50" y="28" width="140" height="64"/>${txt(120,65,'VFD',20)}${line(190,60,228,60)}`;break;
  case 'proximity':inner=`${line(12,60,70,60)}<rect x="70" y="31" width="82" height="58"/>${txt(111,65,'PROX',12)}<path d="M166 43 Q184 60 166 77 M178 33 Q208 60 178 87"/>`;break;
  case 'limit-switch':inner=contact()+`<path d="M120 42 L137 12 L162 12"/><circle cx="164" cy="12" r="4"/>`;break;
  case 'terminal':inner=`${line(12,60,110,60)}<circle cx="120" cy="60" r="10"/>${line(130,60,228,60)}${txt(120,94,'X1:1',11)}`;break;
  case 'capacitor':inner=`${line(12,60,93,60)}${line(93,32,93,88)}${line(147,32,147,88)}${line(147,60,228,60)}${txt(120,108,'C1',11)}`;break;
  default:inner=box('?');
 }
 return `<svg viewBox="0 0 240 120" role="img" aria-label="Representative symbol for ${catalog.find(s=>s.id===id)?.name||'component'}" xmlns="http://www.w3.org/2000/svg"><g ${common}>${inner}</g></svg>`;
}
