// These SVGs are explanatory sketches, not licensed reproductions of a standards database.
const item=(id,name,kind,contexts,aliases,visual,does,distinction,notation='',source='Original Learn Electro educational sketch',license='Original teaching artwork; not an official standards symbol')=>({id,name,kind,contexts,aliases,visual,does,distinction,notation,source,license});

export const catalog=[
  item('no-contact','Normally open contact','Wired control',['control'],['normally open contact','no contact','open contact','two parallel lines','two vertical bars','relay contact open','contactor auxiliary no','13 14'], 'Two separated parallel bars on a control rung.','With its actuator at rest, the contact is open. Operating the linked device closes it and lets current pass through that branch.','This is a physical contact. A PLC XIC looks similar but tests a software bit instead.','—| |—'),
  item('nc-contact','Normally closed contact','Wired control',['control'],['normally closed contact','nc contact','closed contact','two lines with diagonal slash','two bars with slash','stop contact','push to break','21 22'], 'Two parallel bars crossed by a diagonal slash.','With its actuator at rest, the contact is closed. Operating the linked device opens it and interrupts that branch.','“Normal” means the specified unactuated reference state, not necessarily the machine’s safe state.','—|/|—'),
  item('no-pushbutton','Normally open pushbutton','Operator device',['control'],['start button','start pushbutton','momentary pushbutton no','push to make','normally open pushbutton','button open'], 'Normally open contact with a pushbutton actuator above it.','Pressing the button briefly closes the contact and sends a start or other command. A separate holding circuit may keep a starter energized after release.','The pushbutton itself is momentary; any maintained operation comes from the surrounding circuit.','START / NO'),
  item('nc-pushbutton','Normally closed pushbutton','Operator device',['control'],['stop button','stop pushbutton','push to break button','normally closed pushbutton','button with slash','momentary stop'], 'Normally closed contact with a pushbutton actuator.','The contact is closed at rest and opens while the button is pressed, commonly interrupting a control command.','A regular stop button is not automatically an emergency stop or a safety-rated device.','STOP / NC'),
  item('estop','Emergency-stop actuator','Operator device',['control'],['emergency stop','e stop','estop','mushroom button','red mushroom','safety stop'], 'Mushroom-head actuator above a contact depiction.','Manually initiates a stop function in an appropriately engineered safety circuit.','The symbol alone does not establish safety performance or wiring architecture.','E-STOP'),
  item('relay-coil','Relay or contactor coil','Wired control',['control'],['relay coil','contactor coil','coil circle','circle labeled km','circle labeled cr','electromagnet coil','a1 a2'], 'Circle with coil tag between two control wires.','A rated control voltage magnetizes the device and moves its associated contacts.','The coil does not carry the motor’s three-phase load current.','KM1 / A1–A2'),
  item('timer-relay','Timer relay','Wired control',['control'],['timer relay','time delay relay','on delay relay','off delay relay','delay timer','timer contact'], 'A timing relay block or clock-style symbol used in a control circuit.','Delays the change of a contact state for a preset time after energization or de-energization.','The contact timing function is controlled by the relay logic rather than by a simple NO or NC field contact.','TR1 / TD'),
  item('selector-switch','Selector switch','Operator device',['control'],['selector switch','rotary switch','hand off auto switch','hoa switch','mode selector','switch with lever'], 'Rotary or lever selector with multiple position choices.','Selects between operating modes such as hand, off, or auto.','The exact function depends on the contact arrangement and the selected mode.','HS1 / HOA'),
  item('pressure-switch','Pressure switch','Field device',['instrument','control'],['pressure switch','low pressure switch','high pressure switch','ps switch','pressure trip switch','hydraulic pressure switch'], 'Switch symbol with a pressure-actuated actuator or diaphragm.','Changes its electrical contact when pressure crosses a setpoint, on rising or falling pressure depending on the device.','It reports a threshold condition, not a continuous pressure value like a transmitter.','PS1'),
  item('flow-switch','Flow switch','Field device',['instrument','control'],['flow switch','water flow switch','pump flow switch','flow trip switch','paddle switch','flow sensor switch'], 'Switch symbol with a flow-actuated element such as a paddle.','Changes an electrical contact when flow crosses its setpoint; the switching direction depends on the device.','It reports a flow threshold, not necessarily a numeric flow rate.','FS1'),
  item('current-transformer','Current transformer','Power measurement',['power','instrument'],['current transformer','ct transformer','current sense transformer','instrument transformer','feeder ct','ammeters current transformer'], 'A conductor passes through a transformer core marked CT.','Produces a smaller, proportional secondary current so a meter or protective relay can measure primary current.','Never open an energized CT secondary: it can develop hazardous voltage. Follow the equipment procedure and use an approved shorting method.','CT1'),
  item('potential-transformer','Potential transformer','Power measurement',['power','instrument'],['potential transformer','voltage transformer','vt transformer','metering transformer','pt transformer'], 'Two separate windings with a magnetic core between them, tagged PT or VT.','Provides a scaled secondary voltage for metering or protection by magnetic coupling from the primary winding.','The secondary is electrically separate from the primary but can still be hazardous. Do not assume its voltage is safe to touch.','PT1'),
  item('solenoid-valve','Solenoid valve','Field device',['instrument','control'],['solenoid valve','electrical valve','pilot valve','air valve coil','solenoid operated valve','electro pneumatic valve'], 'Valve body with a solenoid coil above it.','Uses electrical energization to shift the valve and control fluid or air flow.','The valve’s port arrangement determines whether it is normally closed, normally open, or directional.','SV1'),
  item('contactor-with-aux','Contactor with auxiliary contact','Motor power',['power','control'],['contactor with auxiliary contact','auxiliary contactor','contactor plus aux','motor starter with aux','km with auxiliary'], 'Three-pole power contactor with an additional separate NO or NC auxiliary contact.','Provides the main motor switching function and feedback or interlock logic in the control circuit.','The auxiliary contact reports state but does not carry the main motor load current.','KM1 + AUX'),
  item('thermal-overload-relay','Thermal overload relay','Motor protection',['control','power'],['thermal overload relay','bimetal overload relay','overload relay','thermal trip relay','ol relay','motor thermal protector'], 'Thermal trip element attached to a relay block or motor protection device.','Trips on excessive heating due to overcurrent or overload conditions.','This is a protection device, not the main contactor.','OLR1'),
  item('hoa-switch','Hand-Off-Auto switch','Operator device',['control'],['hand off auto switch','hoa switch','manual auto selector','mode selector switch','motor HOA switch'], 'Three-position selector marked Hand, Off, and Auto.','Selects between manual control, disabled state, or automatic control.','The switch may drive separate contact sets; verify the control drawing.','HOA'),
  item('digital-input','Digital input block','PLC interface',['control','instrument'],['digital input block','di block','digital input module','field input module','input card','digital input card'], 'PLC input module card symbol showing DI and signal connection.','Reads a field switch or sensor state into the controller as a discrete 0/1 signal.','Input type and common wiring must match the field device and module specification.','DI1'),
  item('digital-output','Digital output block','PLC interface',['control'],['digital output block','do block','digital output module','output card','digital input and output module','do channel'], 'PLC output module card symbol showing DO and power connection.','Energizes an external field device or interface under program control.','Do not assume the output can run the load without checking voltage and current ratings.','DO1'),
  item('analog-input','Analog input block','PLC interface',['instrument','control'],['analog input','ai channel','4-20ma input','0-10v input','analog input module'], 'PLC analog module symbol with signal range annotation.','Reads a variable physical value such as pressure, level, or temperature as a scaled analog signal.','Analog channels require scaling and interface configuration beyond simple on/off logic.','AI1'),
  item('analog-output','Analog output block','PLC interface',['instrument','control'],['analog output','ao channel','4-20ma output','0-10v output','analog output module'], 'PLC analog output module symbol with signal range annotation.','Drives a modulating field device using a scaled analog command.','The field device input range and output type must be compatible.','AO1'),
  item('relay-latch','Seal-in (holding) circuit','Wired control',['control'],['latching relay','seal in relay','hold relay','memory relay','self retaining relay'], 'A holding-path block representing a contact that keeps a relay coil energized after a momentary start input.','After a start input energizes a relay or contactor coil, an auxiliary contact can close a parallel path that keeps the coil energized until the stop path opens.','This is a circuit arrangement, not a special standalone relay. Other latch logic may behave differently.','KM1 AUX'),
  item('pressure-transmitter','Pressure transmitter','Instrumentation',['instrument'],['pressure transmitter','pt transmitter','pressure sensor transmitter','4-20ma pressure transmitter','pressure probe'], 'A transmitter block or gauge symbol with a signal output line.','Measures pressure and sends a proportional analog signal to a controller or indicator.','It is not a switch unless the documentation specifically defines a trip point.','PT'),
  item('flow-transmitter','Flow transmitter','Instrumentation',['instrument'],['flow transmitter','flow meter transmitter','4-20ma flow meter','flow indicator transmitter'], 'Flow meter symbol with a transmitter signal output.','Measures flow and sends a scaled analog signal to the control system.','Flow indication and switching are separate functions.','FT'),
  item('dc-power-supply','DC power supply','Power distribution',['power','control'],['dc power supply','24vdc supply','psu dc','power supply unit','regulated dc supply'], 'Rectifier-style supply block labeled DC.','Converts AC or other input power to a controlled DC output for controls and instrumentation.','The output voltage and polarity must match the connected circuit.','24VDC / PS'),
  item('pushbutton-station','Pushbutton station','Operator device',['control'],['pushbutton station','panel station','operator station','pushbutton panel','mushroom station'], 'A grouped set of pushbuttons or selector keys in a panel.','Provides manual operator inputs for start, stop, reset, or mode selection.','The exact function depends on the arrangement and labeling of the contacts.','PB STN'),
  item('annunciator','Annunciator / alarm panel','Operator device',['control'],['annunciator','alarm panel','fault indicator panel','alarm light box','alarm lamp panel'], 'A panel or block with multiple indicator lamps or alarm windows.','Displays active alarm or fault conditions to operators.','An annunciator is a summary device; it does not identify the underlying fault alone.','ANN'),
  item('thermocouple','Thermocouple','Instrumentation',['instrument'],['thermocouple','temperature sensor','tc sensor','junction sensor','temperature probe'], 'Temperature probe symbol with two wires or a sensor junction.','Measures temperature by a junction voltage generated from the temperature difference.','It is a sensing element, not a switch unless paired with a trip device.','TC'),
  item('level-switch','Level switch','Field device',['instrument','control'],['level switch','float switch','liquid level switch','high level switch','low level switch'], 'Switch symbol with a float or level-detecting actuator.','Changes state when a tank or vessel reaches a set liquid level.','A level switch indicates level state, not continuous level.','LS'),
  item('conveyor-motor','Conveyor motor','Load',['power'],['conveyor motor','belt motor','drive motor','conveyor drive','motorized conveyor'], 'Motor symbol associated with material handling equipment.','Drives the conveyor or mechanical transport equipment.','This is a load device; the control logic may include overload and start-stop functions.','M2'),
  item('contactor-power','Three-pole contactor','Motor power',['power'],['three pole contactor','motor starter contacts','three open switches','three phases through contacts','l1 l2 l3 t1 t2 t3','km main contacts','contactor main poles'], 'Three linked normally open contacts, one per phase.','Applies or removes three-phase power to a motor when its separate coil changes state.','An auxiliary contact gives only indirect pickup feedback.','KM1'),
  item('overload-contact','Overload trip contact (NC)','Motor protection',['control'],['overload contact','overload healthy','ol contact','95 96','thermal trip contact','motor overload normally closed','overload nc'], 'Normally closed control contact tagged OL, often identified 95–96.','Opens the starter control path when the overload relay trips in this common arrangement.','This contact is separate from the current-sensing elements in the motor power path.','OL1 / 95–96'),
  item('overload-sensing','Overload current-sensing element','Motor protection',['power'],['overload sensing','overload heater','thermal overload element','three overload blocks','motor protection current sensing','ol power circuit'], 'Current-sensing element in a motor phase path.','Monitors motor current or heating behavior for overload protection.','It does not replace required short-circuit protection.','OL1'),
  item('breaker','Circuit breaker','Power distribution',['power'],['circuit breaker','breaker','cb','qf','switch with trip','three pole breaker','feeder breaker'], 'Switching contacts in a protected branch, shown here as one-line equipment.','Opens a circuit and can interrupt specified fault current within its ratings.','Ratings, trip functions, and isolation suitability depend on the exact device.','QF1 / CB'),
  item('fuse','Fuse','Power distribution',['power'],['fuse','fusible link','fused circuit','fu symbol','small rectangle in line'], 'Small rectangular fuse element in series with a conductor.','Melts to interrupt excessive current according to its characteristics.','Replacement and coordination must follow equipment documentation.','FU1'),
  item('disconnect','Disconnect switch','Power distribution',['power'],['disconnect','isolator','knife switch','open switch on feeder','switch disconnector'], 'Open knife-switch contact in a power conductor.','Provides a means to disconnect a circuit when applied and rated correctly.','A plain disconnect is not necessarily an overcurrent protective device.','QS1'),
  item('transformer','Transformer','Power distribution',['power'],['transformer','two coils','two windings','magnetic core','step down transformer','primary secondary'], 'Two windings with a core between them.','Transfers AC energy by magnetic coupling and changes voltage according to winding ratio.','A transformer is not a generator; its secondary grounding depends on design.','T1'),
  item('motor-3ph','Three-phase motor','Load',['power'],['motor','three phase motor','circle with m','m inside circle','motor 3 tilde','fan motor','pump motor'], 'Circle marked M and 3~ with three supply leads.','Converts three-phase electrical power into shaft torque.','An auxiliary contact alone cannot prove this motor rotates.','M1 / 3~'),
  item('pe-ground','Protective earth','Grounding',['power','control'],['protective earth','earth ground','ground symbol','three horizontal lines decreasing','pe','equipment ground'], 'Three horizontal bars of decreasing width beneath a conductor.','Identifies the protective equipment grounding connection.','Not the normal motor-current return or a substitute for neutral.','PE'),
  item('pilot-lamp','Pilot light / indicator','Operator device',['control'],['lamp','pilot light','indicator lamp','circle with x','circle with cross','run light','fault light'], 'Circle containing an X.','Lights to communicate status when its circuit is energized.','A lit run lamp may report a command rather than physical motion; trace its circuit.','HL1'),
  item('plc-di','PLC digital input','PLC interface',['control','instrument'],['plc input','digital input','di channel','input module','field switch to plc','input card'], 'Field contact connected to a PLC input block.','Reads an electrical on/off field signal into the controller.','The module’s wiring and input common depend on its specification.','DI'),
  item('plc-do','PLC digital output','PLC interface',['control'],['plc output','digital output','do channel','output module','output card','plc commands coil'], 'PLC output block connected to an external load or interface.','Switches a compatible low-power load or interface under program control.','Check output type and ratings before driving a coil.','DO'),
  item('safety-relay','Safety relay','Safety control',['control','safety'],['safety relay','dual channel safety relay','guard relay','emergency stop safety relay','safety logic relay'], 'Safety relay block with dual-channel logic and reset path.','Monitors designated safety inputs and switches safety outputs according to its configured logic.','A safety relay is not a general-purpose control relay; the complete safety function depends on system design, wiring, and validation.','SR1'),
  item('temperature-switch','Temperature switch','Field device',['instrument','control'],['temperature switch','thermostat switch','high temp switch','temperature trip switch','temp limit switch'], 'Switch symbol with a thermal sensing element.','Changes an electrical contact when temperature crosses its setpoint.','It reports a threshold, not a continuous temperature value like a transmitter.','TS1'),
  item('photoelectric-sensor','Photoelectric sensor','Field device',['instrument','control'],['photoelectric sensor','photo eye','laser sensor','optical sensor','through beam sensor'], 'Sensor block with a light beam path and receiver symbol.','Detects an object using emitted and received light, by interruption or reflection depending on the sensor type.','The drawing does not specify through-beam, retroreflective, or diffuse mode.','PS1'),
  item('light-curtain','Light curtain','Safety device',['safety','instrument'],['light curtain','safety light curtain','optical guard','presence sensing device'], 'Parallel beam sensor array with multiple beams or segments.','Detects when an object interrupts its sensing field and sends a signal to a safety control system.','A light curtain alone does not establish a validated safety function or required stopping performance.','LC1'),
  item('pneumatic-cylinder','Pneumatic cylinder','Actuator',['instrument','control'],['pneumatic cylinder','air cylinder','double acting cylinder','linear actuator'], 'Cylinder body with a piston and a rod extending outward.','Uses compressed air pressure on a piston to produce linear motion.','This simplified sketch does not show port count or prove whether the cylinder is single- or double-acting.','CYL1'),
  item('electric-heater','Electric heater','Load',['power','instrument'],['electric heater','heating element','resistance heater','immersion heater','space heater'], 'Heating element or resistance coil symbol for an electrical load.','Converts electrical energy into heat for a process or space.','The symbol does not specify heater power, control method, or required overcurrent protection.','EH1'),
  item('instrument-air','Instrument air supply','Utility',['instrument','power'],['instrument air','compressed air supply','air header','pneumatic supply','air utility'], 'Utility label indicating a compressed-air supply connection.','Provides clean, dry compressed air as an energy source for pneumatic instruments and actuators.','Instrument air is a utility, not an electrical signal. The required quality and pressure are project-specific.','IA'),
  item('rotameter','Rotameter / variable-area flow meter','Instrumentation',['instrument'],['rotameter','variable area flow meter','float flow meter','flow indicator tube','flow meter tube'], 'Vertical tapered tube with a float indicating flow.','A float rises in a tapered tube as flow increases; its position gives a local flow indication when read against the scale.','It must be installed in the orientation and flow direction specified for the meter; this drawing does not show a scale.','FI'),
  item('battery','Battery','Power source',['power'],['battery','dc battery','backup battery','cell stack','storage battery'], 'A DC source marked BAT with polarity indicated by unequal parallel plates.','Stores chemical energy and supplies DC electrical energy to a circuit.','This sketch indicates a battery source but does not specify cell count, voltage, chemistry, or capacity.','BAT1'),
  item('ups','Uninterruptible power supply','Power distribution',['power','control'],['ups','uninterruptible power supply','battery backup','power backup unit','inverter battery module'], 'Block labeled UPS in a power path.','Provides backup power from stored energy when its input supply is interrupted, and may also condition power depending on design.','Transfer time, runtime, and output quality depend on the UPS topology and load.','UPS1'),
  item('generator','Generator / alternator','Power source',['power'],['generator','alternator','ac generator','prime mover generator','electric generator'], 'Rotating electrical machine marked GEN in a power path.','Converts mechanical input into electrical output by electromagnetic induction.','The symbol does not specify AC or DC output, voltage, frequency, or prime mover.','G1'),
  item('vibration-switch','Vibration switch','Field device',['instrument','control'],['vibration switch','machine vibration switch','shaft vibration trip','vibration monitor switch'], 'Switch block identified VS for a vibration-related trip or status signal.','Changes an output state when measured vibration crosses a configured threshold.','A vibration switch gives a threshold signal; a vibration transmitter or monitor can provide more measurement detail.','VS1'),
  item('speed-sensor','Speed sensor','Field device',['instrument','control'],['speed sensor','tachometer sensor','encoder sensor','rpm sensor','shaft speed switch'], 'Sensor block identified SPD, shown near a rotating shaft.','Detects shaft rotation so a controller or instrument can determine speed.','A speed sensor may provide pulses or an analog signal; it is only an on/off switch when configured as one.','SP1'),
  item('dol-starter','Direct-on-line motor starter','Motor control',['power','control'],['direct on line starter','dol starter','across the line starter','motor starter contactor overload','full voltage motor starter'], 'Simplified block path showing a contactor, overload relay, and motor; phase wiring is omitted.','Connects a compatible motor directly to the supply through a contactor. An overload relay can trip the control circuit if the motor is overloaded.','This is not a complete starter schematic; short-circuit protection, control wiring, ratings, and motor suitability are not shown.','M1 / DOL'),
  item('reversing-starter','Reversing motor starter','Motor control',['power','control'],['reversing starter','forward reverse contactors','reversing contactor pair','motor direction starter','forward reverse motor control'], 'Two labeled direction contactors and a motor; phase connections and interlocks are omitted.','For a compatible three-phase motor, the reversing contactor arrangement swaps two phase connections to reverse rotation.','The contactors need appropriate electrical and mechanical interlocking. This icon is a concept overview, not a wiring diagram.','FWD / REV'),
  item('star-delta-starter','Star-delta motor starter','Motor control',['power','control'],['star delta starter','wye delta starter','star delta motor connection','reduced voltage starter','star delta contactors'], 'Three labeled boxes indicate main, star, and delta contactor roles; winding connections are omitted.','A compatible six-lead motor starts with its windings connected in star, then changes to delta for normal running. This reduces starting current and starting torque compared with starting in delta.','The motor must be designed for this method and the supply voltage. Timing, transition, and protection details are not shown; this is not a wiring diagram.','Y-Δ'),
  item('soft-starter','Soft starter','Motor control',['power'],['soft starter','solid state motor starter','reduced voltage soft start','thyristor motor starter'], 'Power-electronic starter block between the supply and motor.','Gradually increases motor voltage during starting to limit starting current and mechanical shock.','A soft starter controls starting and stopping; unlike a VFD, it usually does not provide continuous speed control.','SS1'),
  item('motor-brake','Motor brake','Motor control',['power','control'],['motor brake','spring applied brake','electromagnetic brake','brake coil motor','shaft holding brake'], 'Brake unit shown beside a motor shaft.','A brake applies friction to resist or stop shaft rotation; an actuator controls the brake mechanism.','Whether the brake applies when energized or de-energized depends on its design. This symbol does not establish a safety function.','BR1'),
  item('motor-thermistor','Motor winding thermistor','Motor protection',['control','instrument'],['motor thermistor','ptc thermistor motor protection','winding temperature sensor','motor thermal sensor','ptc motor'], 'Thermistor sensing element embedded in a motor winding.','Provides a temperature-dependent signal for motor thermal protection.','It is distinct from an overload relay that estimates heating from line current.','P1 / PTC','Original Learn Electro educational sketch','Original drawing; common circuit concept, no third-party symbol artwork copied'),
  item('hvac-compressor','Refrigeration compressor','HVAC / refrigeration',['power','instrument'],['refrigeration compressor','hvac compressor','refrigerant compressor','compressor in refrigeration cycle','scroll compressor symbol'], 'Compressor symbol in a refrigerant circuit with suction and discharge connections.','Raises refrigerant vapor pressure and circulates refrigerant through the refrigeration cycle.','Compressor construction varies; this simplified sketch is not a piping design.','CMP1','Original Learn Electro educational sketch','Original drawing; common circuit concept, no third-party symbol artwork copied'),
  item('evaporator-coil','Evaporator coil','HVAC / refrigeration',['instrument'],['evaporator coil','refrigeration evaporator','cooling coil','hvac cooling coil','evaporator heat exchanger'], 'Heat-exchanger coil on the low-pressure side of a refrigeration circuit.','Absorbs heat as refrigerant evaporates in the coil.','Air-side and refrigerant-side arrangements vary by equipment.','EVAP1','Original Learn Electro educational sketch','Original drawing; common circuit concept, no third-party symbol artwork copied'),
  item('condenser-coil','Condenser coil','HVAC / refrigeration',['instrument'],['condenser coil','refrigeration condenser','hvac condenser','condenser heat exchanger','air cooled condenser'], 'Heat-exchanger coil with a fan indication on the high-pressure side.','Rejects heat as refrigerant condenses to liquid.','The sketch does not specify air-cooled versus water-cooled construction.','COND1','Original Learn Electro educational sketch','Original drawing; common circuit concept, no third-party symbol artwork copied'),
  item('expansion-valve','Thermostatic expansion valve','HVAC / refrigeration',['instrument','control'],['thermostatic expansion valve','txv','refrigerant expansion valve','metering device refrigeration','expansion device hvac'], 'Metering valve and sensing bulb on the evaporator outlet.','Meters refrigerant into the evaporator and regulates superheat in a typical system.','TXV selection and adjustment depend on refrigerant, load, and system design.','TXV1','Original Learn Electro educational sketch','Original drawing; common circuit concept, no third-party symbol artwork copied'),
  item('hvac-thermostat','HVAC thermostat','HVAC control',['control','instrument'],['hvac thermostat','room thermostat','heating cooling thermostat','temperature controller hvac','space thermostat'], 'Room temperature controller with heating and cooling outputs.','Requests heating or cooling to maintain a temperature setpoint.','A thermostat command does not confirm that the equipment has started or delivered capacity.','TSTAT1','Original Learn Electro educational sketch','Original drawing; common circuit concept, no third-party symbol artwork copied'),
  item('hvac-damper','Motorized HVAC damper','HVAC control',['control','instrument'],['motorized damper','hvac damper actuator','air damper','modulating damper','ventilation damper'], 'Damper blade in a duct with an electric actuator.','Regulates airflow through a duct in response to a control signal.','The actuator may be two-position, floating, or modulating; verify its control type.','DMP1','Original Learn Electro educational sketch','Original drawing; common circuit concept, no third-party symbol artwork copied'),
  item('air-filter','Air filter','HVAC equipment',['instrument'],['hvac air filter','duct filter','air handling unit filter','filter bank symbol','air filter element'], 'Filter element spanning an air duct.','Removes particulate matter from moving air in an HVAC system.','Filter pressure drop and efficiency are equipment-specific.','FLT1','Original Learn Electro educational sketch','Original drawing; common circuit concept, no third-party symbol artwork copied'),
  item('pressure-indicator','Pressure indicator (PI)','Process instrumentation',['instrument'],['pressure indicator','pi instrument bubble','pressure gauge pid','local pressure gauge','pressure indication tag pi'], 'Instrument bubble with PI tag connected to a process line.','Displays measured pressure locally or at the instrument location shown.','PI is an indication function; a pressure transmitter or controller has a different role.','PI','Original Learn Electro educational sketch','Original drawing; common process instrumentation convention, not copied artwork'),
  item('temperature-indicator','Temperature indicator (TI)','Process instrumentation',['instrument'],['temperature indicator','ti instrument bubble','temperature gauge pid','local temperature indicator','temperature indication tag ti'], 'Instrument bubble with TI tag connected to a temperature element.','Displays measured temperature at the indicated location.','TI indicates temperature; it does not necessarily provide control output.','TI','Original Learn Electro educational sketch','Original drawing; common process instrumentation convention, not copied artwork'),
  item('level-transmitter','Level transmitter (LT)','Process instrumentation',['instrument','control'],['level transmitter','lt instrument bubble','tank level transmitter','level measurement transmitter','level transmitter tag'], 'Instrument bubble with LT tag and a signal line from a vessel.','Measures vessel level and transmits a corresponding signal to a control or monitoring system.','The sensing technology and output signal are not specified by this simplified sketch.','LT','Original Learn Electro educational sketch','Original drawing; common process instrumentation convention, not copied artwork'),
  item('differential-pressure-transmitter','Differential pressure transmitter (PDT)','Process instrumentation',['instrument','control'],['differential pressure transmitter','dp transmitter','dpt instrument bubble','differential pressure measurement','pressure drop transmitter'], 'Differential pressure instrument with high- and low-side impulse connections.','Measures pressure difference between two process points.','A DP transmitter can infer flow or level only with suitable installation and configuration.','PDT','Original Learn Electro educational sketch','Original drawing; common process instrumentation convention, not copied artwork'),
  item('control-valve','Control valve (final element)','Process instrumentation',['instrument','control'],['control valve','actuated control valve','pneumatic control valve','modulating valve','final control element'], 'Valve body with pneumatic actuator and control signal connection.','Modulates process flow in response to a controller output.','Fail position, characteristic, and actuator details must be read from the project documentation.','CV1','Original Learn Electro educational sketch','Original drawing; common process instrumentation convention, not copied artwork'),
  item('orifice-plate','Orifice plate flow element','Process instrumentation',['instrument'],['orifice plate','flow restriction plate','primary flow element','differential pressure flow element','orifice flow meter'], 'Restriction plate in a pipe with upstream and downstream pressure taps.','Creates a pressure differential used to infer flow in a properly configured measurement system.','The plate alone is not a flow transmitter or a complete measurement loop.','FE1','Original Learn Electro educational sketch','Original drawing; common process instrumentation convention, not copied artwork'),
  item('instrument-signal-converter','I/P signal converter','Process instrumentation',['instrument','control'],['i p converter','current to pressure converter','4-20ma to pneumatic converter','electro pneumatic transducer','signal converter ip'], 'Converter block receiving an electrical signal and delivering pneumatic output.','Converts a current signal into a proportional pneumatic pressure signal.','Ranges and fail behavior vary; check the instrument datasheet and loop documentation.','I/P1','Original Learn Electro educational sketch','Original drawing; common process instrumentation convention, not copied artwork'),
  item('x ic','XIC - Examine If Closed','PLC ladder',['ladder'],['xic','examine if closed','plc normally open','ladder no contact','bit true contact','two vertical lines in ladder'], 'Two upright bars on a PLC ladder rung.','Makes its rung condition true when the addressed bit is 1.','It is a software instruction; it does not prove a physical contact is closed.','XIC / —| |—'),
  item('xio','XIO - Examine If Open','PLC ladder',['ladder'],['xio','examine if open','plc normally closed','ladder nc contact','bit false contact','slashed ladder contact'], 'Two bars with a diagonal slash on a PLC ladder rung.','Makes its rung condition true when the addressed bit is 0.','It tests a bit; it is not necessarily a physical normally closed field contact.','XIO / —|/|—'),
  item('ote','OTE - Output Energize','PLC ladder',['ladder'],['ote','output energize','ladder coil','plc coil','parentheses output','output instruction'], 'Parenthesized output symbol at the right of a rung.','Sets the addressed bit when preceding rung conditions are true and clears it when false.','A program bit or output command is not proof that a motor actually started.','OTE / —( )—'),
  item('vfd','Variable-frequency drive','Motor power',['power'],['vfd','variable frequency drive','inverter drive','ac drive','rectifier inverter motor','speed drive'], 'Block labeled VFD between three-phase input and motor output.','Controls motor speed by generating a controlled-frequency and voltage output.','The motor-side waveform is not ordinary fixed-frequency utility AC.','VFD1'),
  item('proximity','Proximity sensor','Field device',['instrument','control'],['proximity sensor','prox switch','inductive sensor','detect metal without contact','non contact sensor'], 'Sensor block with target-sensing arcs.','Detects a nearby target and sends a signal to controls.','Wiring and output type vary by sensor model.','B1 / PROX'),
  item('limit-switch','Limit switch','Field device',['instrument','control'],['limit switch','mechanical position switch','roller lever switch','end of travel switch','actuated by cam'], 'Switch contact with a mechanical lever actuator.','Changes contact state when a moving part reaches its position.','The contact can be NO or NC; inspect the actual contact marking.','LS1'),
  item('terminal','Terminal block','Connection',['control','power'],['terminal block','terminal strip','numbered terminal','wire landing point','screw terminal','x1 terminal'], 'Small connection circle or block in an uninterrupted conductor.','Provides a labeled point for joining and servicing conductors.','A terminal does not by itself protect or switch the circuit.','X1:1'),
  item('capacitor','Capacitor','Electronic component',['control','power'],['capacitor','two plates','two parallel lines no wire between','capacitance','c1'], 'Two parallel plates separated by a gap.','Stores energy in an electric field and opposes sudden voltage change.','Can resemble a NO contact in a rough verbal description; check circuit context and tag.','C1')
];

const common=`fill="none" stroke="#173b52" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"`;
const line=(x1,y1,x2,y2)=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/>`;
const txt=(x,y,s,size=13)=>`<text x="${x}" y="${y}" text-anchor="middle" font-family="Arial,sans-serif" font-size="${size}" font-weight="700" fill="#173b52" stroke="none">${s}</text>`;
const contact=(nc=false)=>`${line(12,60,93,60)}${line(93,38,93,82)}${line(147,38,147,82)}${line(147,60,228,60)}${nc?line(81,84,158,36):''}`;
const coil=(tag='KM1')=>`${line(12,60,91,60)}<circle cx="120" cy="60" r="29"/>${line(149,60,228,60)}${txt(120,65,tag,12)}`;
const box=(label)=>`${line(12,60,55,60)}<rect x="55" y="27" width="130" height="66" rx="4"/>${line(185,60,228,60)}${txt(120,65,label)}`;

export function symbolSvg(id){
 let inner='';
 switch(id){
  case 'no-contact':case 'x ic':inner=contact();break;
  case 'nc-contact':case 'xio':case 'overload-contact':inner=contact(true)+(id==='overload-contact'?txt(120,107,'OL1 95–96',10):'');break;
  case 'no-pushbutton':case 'nc-pushbutton':inner=contact(id==='nc-pushbutton')+line(120,16,120,40)+line(101,16,139,16);break;
  case 'estop':inner=contact(true)+line(120,18,120,39)+`<path d="M95 18 Q120 -5 145 18 Z"/>`;break;
  case 'relay-coil':inner=coil();break;
  case 'timer-relay':inner=`${line(12,60,70,60)}<circle cx="112" cy="60" r="42"/><path d="M112 60 L112 32 M112 60 L138 60 M112 60 L96 76"/>${line(154,60,228,60)}${txt(112,105,'TR',12)}`;break;
  case 'selector-switch':inner=`${line(12,60,72,60)}<circle cx="100" cy="60" r="4" fill="#173b52"/><path d="M100 60 L132 36 L150 60 L132 84 Z"/><path d="M150 60 L220 60"/>${txt(120,104,'HOA',11)}`;break;
  case 'pressure-switch':inner=`${line(18,60,75,60)}<path d="M75 26 Q110 26 110 60 Q110 94 75 94 Q60 94 60 80 L60 40 Q60 26 75 26"/><path d="M110 60 L178 60"/><circle cx="188" cy="60" r="10"/>${txt(110,103,'PS',11)}`;break;
  case 'flow-switch':inner=`${line(18,60,70,60)}<path d="M70 32 L112 32 L140 60 L112 88 L70 88 Z"/><path d="M140 60 L185 60"/><path d="M170 76 Q185 54 198 76"/>${txt(120,102,'FS',11)}`;break;
  case 'current-transformer':inner=`${line(18,60,78,60)}<circle cx="119" cy="60" r="38"/><circle cx="119" cy="60" r="18" fill="none"/><path d="M119 22 L119 98 M81 60 L157 60"/>${line(160,60,228,60)}${txt(120,104,'CT',11)}`;break;
  case 'potential-transformer':inner=`${line(12,60,62,60)}<path d="M62 60 c0 -20 24 -20 24 0 c0 20 24 20 24 0"/><line x1="118" y1="20" x2="118" y2="100"/><line x1="124" y1="20" x2="124" y2="100"/><path d="M130 60 c0 -20 24 -20 24 0 c0 20 24 20 24 0"/>${line(178,60,228,60)}${txt(120,110,'PT',11)}`;break;
  case 'solenoid-valve':inner=`${line(12,60,62,60)}<path d="M62 32 L110 32 L110 88 L62 88 Z"/><path d="M110 60 L166 60"/><path d="M166 34 L166 86"/><path d="M180 34 L180 86"/><path d="M180 34 L198 34 L198 86 L180 86"/>${txt(120,104,'SV',11)}`;break;
  case 'contactor-with-aux':inner=[32,60,88].map(y=>`${line(20,y,90,y)}${line(90,y-10,90,y+10)}${line(130,y-10,130,y+10)}${line(130,y,204,y)}`).join('')+`${line(170,30,170,90)}${line(182,30,182,90)}${line(182,60,220,60)}${txt(120,110,'KM1 + AUX',8)}`;break;
  case 'thermal-overload-relay':inner=`${line(20,60,85,60)}<rect x="85" y="32" width="84" height="56"/><path d="M104 48 H150 M104 60 H150 M104 72 H150"/>${line(169,60,228,60)}${txt(120,104,'OLR',11)}`;break;
  case 'hoa-switch':inner=`${line(18,60,70,60)}<circle cx="97" cy="60" r="6" fill="#173b52"/><path d="M97 60 L128 35 L150 60 L128 85 Z"/><text x="110" y="104" text-anchor="middle" font-family="Arial,sans-serif" font-size="11" font-weight="700" fill="#173b52">H-O-A</text>${line(150,60,228,60)}`;break;
  case 'digital-input':inner=`${line(20,60,60,60)}<rect x="60" y="28" width="100" height="64"/>${txt(110,65,'DI',16)}${line(160,60,228,60)}`;break;
  case 'digital-output':inner=`${line(20,60,60,60)}<rect x="60" y="28" width="100" height="64"/>${txt(110,65,'DO',16)}${line(160,60,228,60)}`;break;
  case 'analog-input':inner=`${line(20,60,60,60)}<rect x="60" y="28" width="100" height="64"/>${txt(110,65,'AI',16)}${line(160,60,228,60)}`;break;
  case 'analog-output':inner=`${line(20,60,60,60)}<rect x="60" y="28" width="100" height="64"/>${txt(110,65,'AO',16)}${line(160,60,228,60)}`;break;
  case 'relay-latch':inner=`${line(12,60,70,60)}<rect x="70" y="30" width="90" height="60"/>${line(160,60,228,60)}${txt(115,67,'LATCH',10)}`;break;
  case 'pressure-transmitter':inner=`${line(12,60,72,60)}<circle cx="116" cy="60" r="31"/><path d="M116 29 L116 90 M85 60 L147 60"/>${line(147,60,228,60)}${txt(116,101,'PT',11)}`;break;
  case 'flow-transmitter':inner=`${line(12,60,70,60)}<path d="M70 28 L121 28 L150 60 L121 92 L70 92 Z"/><path d="M150 60 L185 60"/><path d="M168 44 L198 44 L198 76 L168 76"/>${txt(118,103,'FT',11)}`;break;
  case 'dc-power-supply':inner=`${line(12,60,62,60)}<rect x="62" y="28" width="110" height="64"/>${txt(117,65,'24VDC',12)}${line(172,60,228,60)}`;break;
  case 'pushbutton-station':inner=`${line(12,60,58,60)}<rect x="58" y="18" width="112" height="84" rx="6"/>${line(170,60,228,60)}${txt(114,65,'PB',16)}`;break;
  case 'annunciator':inner=`${line(12,60,58,60)}<rect x="58" y="22" width="112" height="76"/><circle cx="86" cy="60" r="12"/><circle cx="116" cy="60" r="12"/><circle cx="146" cy="60" r="12"/>${line(170,60,228,60)}`;break;
  case 'thermocouple':inner=`${line(12,60,78,60)}<path d="M78 60 L118 60 L128 36 L138 60 L148 84 L158 60 L168 60"/>${line(168,60,228,60)}${txt(118,98,'TC',11)}`;break;
  case 'level-switch':inner=`${line(18,60,80,60)}<path d="M80 36 L80 84 L120 84 L120 36 Z"/><path d="M120 60 L176 60"/><circle cx="188" cy="60" r="12"/>${txt(110,104,'LS',11)}`;break;
  case 'conveyor-motor':inner=`${line(12,35,75,35)}${line(12,60,75,60)}${line(12,85,75,85)}<circle cx="135" cy="60" r="53"/>${txt(135,59,'M',26)}${line(175,60,228,60)}`;break;
  case 'ote':inner=`${line(12,60,89,60)}<path d="M109 36 Q88 60 109 84 M131 36 Q152 60 131 84"/>${line(151,60,228,60)}`;break;
  case 'contactor-power':inner=[32,60,88].map(y=>`${line(25,y,100,y)}${line(100,y-10,100,y+10)}${line(140,y-10,140,y+10)}${line(140,y,215,y)}`).join('')+txt(120,113,'KM1',10);break;
  case 'overload-sensing':inner=[32,60,88].map(y=>`${line(20,y,90,y)}<rect x="90" y="${y-10}" width="60" height="20"/>${line(150,y,220,y)}${txt(120,y+4,'OL',9)}`).join('');break;
  case 'breaker':inner=[33,60,87].map(y=>`${line(20,y,98,y)}<circle cx="98" cy="${y}" r="2" fill="#173b52"/><circle cx="143" cy="${y}" r="2" fill="#173b52"/>${line(98,y,133,y-15)}${line(143,y,220,y)}`).join('');break;
  case 'disconnect':inner=`${line(12,60,95,60)}<circle cx="95" cy="60" r="2" fill="#173b52"/>${line(95,60,145,35)}<circle cx="151" cy="60" r="2" fill="#173b52"/>${line(151,60,228,60)}`;break;
  case 'fuse':inner=`${line(12,60,85,60)}<rect x="85" y="44" width="70" height="32"/>${line(85,60,155,60)}${line(155,60,228,60)}`;break;
  case 'transformer':inner=`${line(12,60,65,60)}<path d="M65 60 c0 -28 30 -28 30 0 c0 28 30 28 30 0 M135 60 c0 -28 30 -28 30 0 c0 28 30 28 30 0"/>${line(195,60,228,60)}${line(128,18,128,102)}${line(133,18,133,102)}`;break;
  case 'motor-3ph':inner=`${line(12,35,75,35)}${line(12,60,75,60)}${line(12,85,75,85)}<circle cx="135" cy="60" r="53"/>${txt(135,59,'M',26)}${txt(135,80,'3~',13)}`;break;
  case 'pe-ground':inner=`${line(120,10,120,55)}${line(67,55,173,55)}${line(84,68,156,68)}${line(100,81,140,81)}${line(112,94,128,94)}`;break;
  case 'pilot-lamp':inner=`${line(12,60,82,60)}<circle cx="120" cy="60" r="38"/>${line(94,34,146,86)}${line(146,34,94,86)}${line(158,60,228,60)}`;break;
  case 'plc-di':inner=`${line(12,60,66,60)}${line(66,42,66,78)}${line(91,42,91,78)}${line(91,60,107,60)}<rect x="107" y="28" width="109" height="64"/>${txt(162,65,'PLC DI',13)}`;break;
  case 'plc-do':inner=`<rect x="18" y="28" width="112" height="64"/>${txt(74,65,'PLC DO',13)}${line(130,60,185,60)}<circle cx="199" cy="60" r="14"/>`;break;
  case 'safety-relay':inner=`${line(12,60,66,60)}<rect x="66" y="32" width="110" height="56"/>${txt(121,65,'SR',16)}${line(176,60,228,60)}${line(96,28,96,92)}${line(140,28,140,92)}`;break;
  case 'temperature-switch':inner=`${line(20,60,74,60)}<path d="M74 32 L108 32 L108 88 L74 88 Z"/><path d="M108 60 L176 60"/><circle cx="190" cy="60" r="12"/>${txt(95,104,'TS',11)}`;break;
  case 'photoelectric-sensor':inner=`${line(20,60,70,60)}<rect x="70" y="30" width="88" height="60"/>${txt(114,65,'OPT',12)}${line(158,60,220,60)}${line(120,18,120,28)}${line(120,92,120,102)}${line(120,18,164,18)}${line(120,102,164,102)}`;break;
  case 'light-curtain':inner=`${line(12,60,60,60)}<rect x="60" y="20" width="138" height="80"/>${txt(129,65,'LIGHT CURTAIN',8)}${line(198,60,228,60)}${Array.from({length:5},(_,i)=>`<line x1="85" y1="28" x2="85" y2="92"/>`).join('')}`;break;
  case 'pneumatic-cylinder':inner=`${line(18,60,60,60)}<rect x="60" y="28" width="78" height="64"/><path d="M138 28 L138 92"/><line x1="138" y1="60" x2="196" y2="60"/><line x1="196" y1="28" x2="196" y2="92"/>${txt(99,25,'CYL',11)}`;break;
  case 'electric-heater':inner=`${line(12,60,74,60)}<path d="M74 34 H124 V86 H74 Z"/><path d="M124 34 H160 V86 H124 Z"/><line x1="160" y1="60" x2="228" y2="60"/>${txt(120,104,'HEAT',11)}`;break;
  case 'instrument-air':inner=`${line(12,60,76,60)}<circle cx="116" cy="60" r="40"/><path d="M116 20 L116 100 M76 60 L156 60"/><line x1="156" y1="60" x2="228" y2="60"/>${txt(116,110,'AIR',11)}`;break;
  case 'rotameter':inner=`${line(12,60,82,60)}<path d="M82 30 L82 90 L156 90 L156 30 Z"/><path d="M96 90 L96 30 L142 30 L142 90"/><path d="M124 30 L124 90"/><line x1="156" y1="60" x2="228" y2="60"/>${txt(119,104,'FI',11)}`;break;
  case 'battery':inner=`${line(12,60,76,60)}<path d="M76 42 H106 V78 H76 Z"/><path d="M106 32 V88"/><path d="M122 32 V88"/><path d="M122 60 H184"/><line x1="184" y1="60" x2="228" y2="60"/>${txt(96,104,'BAT',11)}`;break;
  case 'ups':inner=`${line(12,60,54,60)}<rect x="54" y="28" width="118" height="64"/>${txt(113,65,'UPS',17)}${line(172,60,228,60)}`;break;
  case 'generator':inner=`${line(12,60,68,60)}<circle cx="112" cy="60" r="44"/><path d="M112 16 L112 104 M68 60 L156 60"/><line x1="156" y1="60" x2="228" y2="60"/>${txt(112,110,'GEN',11)}`;break;
  case 'vibration-switch':inner=`${line(18,60,76,60)}<path d="M76 30 Q112 18 148 30 Q180 42 168 60 Q180 78 148 90 Q112 102 76 90 Z"/><path d="M168 60 L220 60"/>${txt(118,102,'VS',10)}`;break;
  case 'speed-sensor':inner=`${line(12,60,68,60)}<circle cx="110" cy="60" r="42"/><path d="M110 18 L110 102 M68 60 L152 60"/><path d="M152 60 L228 60"/><path d="M110 60 L148 30"/>${txt(110,106,'SPD',10)}`;break;
  case 'dol-starter':inner=`${line(10,60,45,60)}<rect x="45" y="32" width="52" height="56"/>${txt(71,65,'KM',12)}<rect x="108" y="32" width="52" height="56"/>${txt(134,65,'OL',12)}${line(160,60,190,60)}<circle cx="207" cy="60" r="17"/>${txt(207,65,'M',12)}`;break;
  case 'reversing-starter':inner=`<rect x="24" y="24" width="74" height="48"/>${txt(61,53,'FWD',11)}<rect x="24" y="78" width="74" height="34"/>${txt(61,100,'REV',10)}<line x1="98" y1="48" x2="160" y2="48"/><line x1="98" y1="95" x2="160" y2="72"/><circle cx="194" cy="60" r="27"/>${txt(194,65,'M',17)}${line(160,48,170,48)}${line(160,72,170,72)}`;break;
  case 'star-delta-starter':inner=`<rect x="22" y="30" width="58" height="60"/>${txt(51,65,'MAIN',10)}<rect x="91" y="30" width="58" height="60"/>${txt(120,65,'STAR',10)}<rect x="160" y="30" width="58" height="60"/>${txt(189,65,'DELTA',9)}${line(80,60,91,60)}${line(149,60,160,60)}${txt(120,108,'Y - Δ',12)}`;break;
  case 'soft-starter':inner=`${line(12,60,48,60)}<rect x="48" y="28" width="142" height="64"/>${txt(119,57,'SOFT',14)}${txt(119,75,'STARTER',10)}${line(190,60,228,60)}`;break;
  case 'motor-brake':inner=`${line(12,60,58,60)}<circle cx="106" cy="60" r="35"/>${txt(106,65,'M',18)}<rect x="153" y="38" width="22" height="44"/>${line(175,60,228,60)}${txt(164,30,'BR',10)}`;break;
  case 'motor-thermistor':inner=`${line(12,60,68,60)}<path d="M68 60 L92 38 L116 82 L140 38 L164 82 L188 60"/>${line(188,60,228,60)}${txt(128,106,'PTC',11)}`;break;
  case 'hvac-compressor':inner=`${line(12,60,56,60)}<circle cx="112" cy="60" r="46"/>${txt(112,65,'CMP',13)}${line(112,14,112,2)}${line(158,60,228,60)}${txt(112,112,'COMPRESSOR',8)}`;break;
  case 'evaporator-coil':inner=`${line(12,60,56,60)}<path d="M56 34 H176 V86 H56 Z"/><path d="M68 34 L88 86 L108 34 L128 86 L148 34 L168 86"/>${line(176,60,228,60)}${txt(116,105,'EVAP',10)}`;break;
  case 'condenser-coil':inner=`${line(12,60,42,60)}<path d="M42 34 H158 V86 H42 Z"/><path d="M50 34 L70 86 L90 34 L110 86 L130 34 L150 86"/><circle cx="192" cy="60" r="28"/>${line(178,46,206,74)}${line(206,46,178,74)}${txt(100,105,'COND',10)}`;break;
  case 'expansion-valve':inner=`${line(12,60,83,60)}<path d="M83 38 L120 60 L83 82 Z M157 38 L120 60 L157 82 Z"/><line x1="120" y1="20" x2="120" y2="37"/><circle cx="120" cy="14" r="7"/><line x1="157" y1="60" x2="228" y2="60"/>${txt(120,108,'TXV',10)}`;break;
  case 'hvac-thermostat':inner=`<rect x="65" y="20" width="110" height="80" rx="4"/>${txt(120,48,'TSTAT',12)}${txt(120,72,'H / C',11)}${line(12,60,65,60)}${line(175,60,228,60)}`;break;
  case 'hvac-damper':inner=`${line(12,60,54,60)}<rect x="54" y="36" width="128" height="48"/>${line(70,77,164,43)}<circle cx="190" cy="60" r="20"/>${txt(190,65,'A',13)}${line(182,60,170,60)}`;break;
  case 'air-filter':inner=`${line(12,60,66,60)}<path d="M66 32 L156 32 L134 60 L156 88 L66 88 L88 60 Z"/>${line(156,60,228,60)}${txt(111,65,'F',14)}`;break;
  case 'pressure-indicator':inner=`${line(12,60,80,60)}<circle cx="120" cy="60" r="36"/>${txt(120,57,'PI',15)}${line(120,60,139,43)}${txt(120,108,'PRESSURE',8)}`;break;
  case 'temperature-indicator':inner=`${line(12,60,80,60)}<circle cx="120" cy="60" r="36"/>${txt(120,57,'TI',15)}${line(120,60,139,43)}${txt(120,108,'TEMP',8)}`;break;
  case 'level-transmitter':inner=`<path d="M74 32 H166 V88 H74 Z"/><path d="M74 70 Q120 56 166 70"/><circle cx="120" cy="18" r="18"/>${txt(120,23,'LT',12)}${line(120,36,120,32)}${line(166,60,220,60)}`;break;
  case 'differential-pressure-transmitter':inner=`<circle cx="120" cy="60" r="31"/>${txt(120,65,'PDT',12)}${line(12,38,89,38)}${line(12,82,89,82)}${line(151,60,228,60)}${txt(34,31,'H',9)}${txt(34,99,'L',9)}`;break;
  case 'control-valve':inner=`${line(12,72,85,72)}<path d="M85 48 L120 72 L85 96 Z M155 48 L120 72 L155 96 Z"/><line x1="120" y1="48" x2="120" y2="22"/><path d="M94 22 L146 22 L120 48 Z"/><line x1="155" y1="72" x2="228" y2="72"/>${txt(120,116,'CV',10)}`;break;
  case 'orifice-plate':inner=`${line(12,60,92,60)}<line x1="102" y1="30" x2="102" y2="90"/><line x1="138" y1="30" x2="138" y2="90"/>${line(148,60,228,60)}${line(102,30,102,12)}${line(138,30,138,12)}<circle cx="102" cy="10" r="4"/><circle cx="138" cy="10" r="4"/>${txt(120,108,'FE',10)}`;break;
  case 'instrument-signal-converter':inner=`${line(12,60,58,60)}<rect x="58" y="28" width="124" height="64"/>${txt(120,55,'I/P',18)}${txt(120,74,'4-20 mA',8)}${line(182,60,228,60)}${txt(120,108,'PNEUMATIC OUT',8)}`;break;
  case 'vfd':inner=`${line(12,60,50,60)}<rect x="50" y="28" width="140" height="64"/>${txt(120,65,'VFD',20)}${line(190,60,228,60)}`;break;
  case 'proximity':inner=`${line(12,60,70,60)}<rect x="70" y="31" width="82" height="58"/>${txt(111,65,'PROX',12)}<path d="M166 43 Q184 60 166 77 M178 33 Q208 60 178 87"/>`;break;
  case 'limit-switch':inner=contact()+`<path d="M120 42 L137 12 L162 12"/><circle cx="164" cy="12" r="4"/>`;break;
  case 'terminal':inner=`${line(12,60,110,60)}<circle cx="120" cy="60" r="10"/>${line(130,60,228,60)}${txt(120,94,'X1:1',11)}`;break;
  case 'capacitor':inner=`${line(12,60,93,60)}${line(93,32,93,88)}${line(147,32,147,88)}${line(147,60,228,60)}${txt(120,108,'C1',11)}`;break;
  default:inner=box('?');
 }
 return `<svg viewBox="0 0 240 120" role="img" aria-label="Representative symbol for ${catalog.find(s=>s.id===id)?.name||'component'}" xmlns="http://www.w3.org/2000/svg"><g ${common}>${inner}</g></svg>`;
}
